"""
Normalized catalog schema and builders.
"""
from datetime import datetime, timezone
from typing import Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field

from app.models import Device
from app.version import CATALOG_SCHEMA_VERSION


class EquipmentTypeDefinition(BaseModel):
    id: str
    key: str
    name: str
    required_fields: List[str] = Field(default_factory=list)
    lifecycle_status: str = "verified"
    description: Optional[str] = None


class CatalogPortDefinition(BaseModel):
    name: str
    port_type: str
    speed_mbps: Optional[int] = None
    power_watts: Optional[float] = None


class InterfaceCapacityDefinition(BaseModel):
    speed_mbps: Optional[int] = None
    power_watts: Optional[float] = None
    port_count: Optional[int] = None
    poe_budget_watts: Optional[float] = None


class InterfaceDefinition(BaseModel):
    id: str
    label: str
    kind: str
    role: str = "secondary"
    direction: str = "bidirectional"
    connection_mode: str = "data"
    visible_by_default: bool = True
    capacity: InterfaceCapacityDefinition = Field(default_factory=InterfaceCapacityDefinition)


class StatusHistoryEntry(BaseModel):
    from_status: str
    to_status: str
    changed_at: str
    changed_by: str = "system"
    note: Optional[str] = None


class EquipmentModelDefinition(BaseModel):
    id: str
    key: str
    type_key: str
    name: str
    manufacturer: str
    model: str
    lifecycle_status: str = "verified"
    schema_version: str = CATALOG_SCHEMA_VERSION
    updated_at: Optional[str] = None
    updated_by: Optional[str] = None
    power_consumption_watts: Optional[float] = None
    resolution: Optional[str] = None
    storage_capacity_gb: Optional[int] = None
    bandwidth_requires_mbps: Optional[int] = None
    ports: List[CatalogPortDefinition] = Field(default_factory=list)
    interfaces: List[InterfaceDefinition] = Field(default_factory=list)
    status_history: List[StatusHistoryEntry] = Field(default_factory=list)


class CompatibilityRuleDefinition(BaseModel):
    id: str
    rule_key: str
    from_port_type: str
    to_port_type: str
    allowed_cables: List[str] = Field(default_factory=list)
    max_length_meters: Optional[int] = None
    lifecycle_status: str = "verified"


class NormalizedCatalogResponse(BaseModel):
    schema_version: str = CATALOG_SCHEMA_VERSION
    generated_at: str
    equipment_types: List[EquipmentTypeDefinition]
    equipment_models: List[EquipmentModelDefinition]
    compatibility_rules: List[CompatibilityRuleDefinition]


TYPE_DEFINITIONS: Dict[str, EquipmentTypeDefinition] = {
    "camera": EquipmentTypeDefinition(
        id="type-camera",
        key="camera",
        name="Camera",
        required_fields=["name", "device_type", "model", "manufacturer", "resolution", "ports"],
        description="Video capture endpoint device.",
    ),
    "nvr": EquipmentTypeDefinition(
        id="type-nvr",
        key="nvr",
        name="NVR",
        required_fields=["name", "device_type", "model", "manufacturer", "storage_capacity_gb", "ports"],
        description="Network video recorder.",
    ),
    "switch": EquipmentTypeDefinition(
        id="type-switch",
        key="switch",
        name="Switch",
        required_fields=["name", "device_type", "model", "manufacturer", "ports", "power_consumption_watts"],
        description="Network switching device.",
    ),
    "server": EquipmentTypeDefinition(
        id="type-server",
        key="server",
        name="Server",
        required_fields=["name", "device_type", "model", "manufacturer", "storage_capacity_gb", "ports"],
        description="Compute/storage server.",
    ),
    "ups": EquipmentTypeDefinition(
        id="type-ups",
        key="ups",
        name="UPS",
        required_fields=["name", "device_type", "model", "manufacturer", "power_consumption_watts", "ports"],
        description="Uninterruptible power supply.",
    ),
    "gateway": EquipmentTypeDefinition(
        id="type-gateway",
        key="gateway",
        name="Gateway",
        required_fields=["name", "device_type", "model", "manufacturer", "ports"],
        description="Gateway/integration node.",
    ),
    "access_controller": EquipmentTypeDefinition(
        id="type-access-controller",
        key="access_controller",
        name="Access Controller",
        required_fields=["name", "device_type", "model", "manufacturer", "ports"],
        description="Access control device.",
    ),
}


def _default_type_definition(type_key: str) -> EquipmentTypeDefinition:
    return EquipmentTypeDefinition(
        id=f"type-{type_key}",
        key=type_key,
        name=type_key.replace("_", " ").title(),
        required_fields=["name", "device_type", "model", "manufacturer", "ports"],
        lifecycle_status="draft",
        description="Autogenerated type definition.",
    )


def _make_compatibility_rules() -> List[CompatibilityRuleDefinition]:
    return [
        CompatibilityRuleDefinition(
            id="rule-eth-eth",
            rule_key="ethernet_to_ethernet",
            from_port_type="ethernet",
            to_port_type="ethernet",
            allowed_cables=["CAT5e", "CAT6", "OPTICAL"],
            max_length_meters=100,
        ),
        CompatibilityRuleDefinition(
            id="rule-serial-serial",
            rule_key="serial_to_serial",
            from_port_type="serial",
            to_port_type="serial",
            allowed_cables=["SERIAL"],
            max_length_meters=15,
        ),
        CompatibilityRuleDefinition(
            id="rule-power-power",
            rule_key="power_to_power",
            from_port_type="power",
            to_port_type="power",
            allowed_cables=["POWER"],
            max_length_meters=30,
        ),
    ]


def derive_interfaces_from_ports(
    ports: List[CatalogPortDefinition],
    *,
    device_type: Optional[str] = None,
    name: Optional[str] = None,
    model: Optional[str] = None,
    key: Optional[str] = None,
    power_consumption_watts: Optional[float] = None,
) -> List[InterfaceDefinition]:
    if not ports:
        return []

    interfaces: List[InterfaceDefinition] = []
    poe_hint = " ".join(value.lower() for value in [device_type, name, model, key] if value)
    inferred_poe_switch = str(device_type or "").lower() == "switch" and "poe" in poe_hint
    has_poe_like_interface = any("poe" in str(port.port_type).lower() for port in ports) or inferred_poe_switch
    for index, port in enumerate(ports):
        port_type = str(port.port_type).lower()
        kind = "ethernet"
        role = "secondary"
        connection_mode = "data"
        label = port.name
        port_power_budget = port.power_watts

        if "poe" in port_type or (inferred_poe_switch and "ethernet" in port_type):
            kind = "poe_ethernet"
            role = "primary"
            connection_mode = "combined"
            label = "PoE Access" if inferred_poe_switch else "PoE / LAN"
            port_power_budget = (
                port.power_watts
                if port.power_watts is not None
                else (
                    float(power_consumption_watts) / max(len(ports), 1)
                    if inferred_poe_switch and power_consumption_watts
                    else None
                )
            )
        elif "ethernet" in port_type:
            kind = "ethernet"
            role = "primary" if index == 0 else "secondary"
            connection_mode = "data"
            label = "LAN" if index == 0 else port.name
        elif "power" in port_type:
            kind = "power_input"
            role = "secondary"
            connection_mode = "power"
            label = "Power In"
        elif "serial" in port_type:
            kind = "serial"
            role = "advanced"
            connection_mode = "data"
        elif "fiber" in port_type or "optical" in port_type or "sfp" in port_type:
            kind = "fiber"
            role = "primary"
            connection_mode = "data"
            label = "Fiber"

        interfaces.append(
            InterfaceDefinition(
                id=f"if-{index}-{port.name.lower().replace(' ', '-')}",
                label=label,
                kind=kind,
                role=role,
                connection_mode=connection_mode,
                visible_by_default=role != "advanced" and not (has_poe_like_interface and kind == "power_input"),
                capacity=InterfaceCapacityDefinition(
                    speed_mbps=port.speed_mbps,
                    power_watts=port.power_watts,
                    poe_budget_watts=port_power_budget if kind == "poe_ethernet" else None,
                ),
            )
        )
    return interfaces


def build_normalized_catalog(equipment_catalog: Dict[str, Device]) -> NormalizedCatalogResponse:
    generated_at = datetime.now(timezone.utc).isoformat()
    type_keys = sorted({str(device.device_type) for device in equipment_catalog.values()})
    equipment_types: List[EquipmentTypeDefinition] = [
        TYPE_DEFINITIONS.get(type_key, _default_type_definition(type_key)) for type_key in type_keys
    ]

    equipment_models: List[EquipmentModelDefinition] = []
    for key, device in equipment_catalog.items():
        equipment_models.append(
            EquipmentModelDefinition(
                id=str(uuid4()),
                key=key,
                type_key=str(device.device_type),
                name=device.name,
                manufacturer=device.manufacturer,
                model=device.model,
                updated_at=generated_at,
                updated_by="system",
                power_consumption_watts=device.power_consumption_watts,
                resolution=device.resolution,
                storage_capacity_gb=device.storage_capacity_gb,
                bandwidth_requires_mbps=device.bandwidth_requires_mbps,
                ports=[
                    CatalogPortDefinition(
                        name=port.name,
                        port_type=str(port.port_type),
                        speed_mbps=port.speed_mbps,
                        power_watts=port.power_watts,
                    )
                    for port in device.ports
                ],
                interfaces=derive_interfaces_from_ports(
                    [
                        CatalogPortDefinition(
                            name=port.name,
                            port_type=str(port.port_type),
                            speed_mbps=port.speed_mbps,
                            power_watts=port.power_watts,
                        )
                        for port in device.ports
                    ],
                    device_type=str(device.device_type),
                    name=device.name,
                    model=device.model,
                    key=key,
                    power_consumption_watts=device.power_consumption_watts,
                ),
            )
        )

    return NormalizedCatalogResponse(
        generated_at=generated_at,
        equipment_types=equipment_types,
        equipment_models=equipment_models,
        compatibility_rules=_make_compatibility_rules(),
    )
